name: Run Python Script and Save Output

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Python script and save output
        id: run_script
        run: |
          output=$(python -c "import src.main; print(src.main.main())")
          echo "Output: $output"

      - name: Save output to file
        run: echo "$output" > output.ttl

      - name: Upload output file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-output
          path: entur-staging.ttl
          overwrite: true
